### ISSUE TITLE
Is there any more haptics?

### ISSUE THREAD

**Issue by tobedecided0601** [martynaskre/node-mac-haptics#1]
First, I appreciates that you make this thing so I can integrate it into my NodeJS project. However, when I test out all 6 different types of haptics (feedback and performaceTime), they seem to be the same haptics.

Is there anyway to change like their duration, intensity and other type of haptics that isn't mentioned here? I see other apps that have more haptic variants than the one provided here.

**Comment by tobedecided0601** [comment]
I also noticed that some other apps are able to play haptics while the user's finger wasn't touching the touchpad, while this package wasn't be able to do that. Is this a NodeJS limitation ?

**Comment by martynaskre** [comment]
Thanks for using this package! I think this is not a NodeJS limitation because this barebones implementation of haptic feedback functionality. It would need further research to implement more complex haptic feedback patterns. If you can investigate more, I would happily check the PR.

**Comment by tobedecided0601** [comment]
After a bit of research, I do believe that complex patterns are just pattern templates that Apple provided for developers so they can just plug and play.

My theory is that complex patterns are long period of vibration being applied here. I could be wrong tho.
